#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;

die "USAGE $0 <file> <condition>" unless @ARGV;

my $F;
open $F, "<", $ARGV[0] or die "Unable to open file $ARGV[0]: $!";
my @lines = <$F>;
my $data = join "", @lines;
no strict;
my $state = eval $data;
use strict;

print "state:\n" , Dumper($state);

my $cond = $ARGV[1];
exit 1 unless eval $cond;

print "state: OK\n";
