#!/bin/sh
#
# $FreeBSD: head/mail/exim/files/exim.in 340872 2014-01-24 00:14:07Z mat $
#

# PROVIDE: advancedfiltering_submission
# REQUIRE: LOGIN
# KEYWORD: shutdown
#	we make mail start late, so that things like .forward's are not
#	processed until the system is fully operational

#
# Add the following lines to /etc/rc.conf to enable exim:
#
#advancedfiltering_submission_exim_enable="YES"
#
# See exim(8) for flags
#

. /etc/rc.subr

name=advancedfiltering_submission_exim
rcvar=advancedfiltering_submission_exim_enable
command=/usr/local/sbin/exim
pidfile=/usr/local/advancedfiltering/submission/exim/spool/exim.pid
required_dirs="/usr/local/advancedfiltering/submission/exim/log /usr/local/advancedfiltering/submission/exim/spool"
advancedfiltering_conffile=/usr/local/advancedfiltering/submission/exim/configure
required_files="$advancedfiltering_conffile"
stop_postcmd=stop_postcmd
extra_commands="reload"

stop_postcmd()
{
  rm -f $pidfile
}

# read settings, set default values
load_rc_config $name

: ${advancedfiltering_submission_exim_enable="NO"}
: ${advancedfiltering_submission_exim_flags="-bd -q1m -C $advancedfiltering_conffile -oP $pidfile"}

run_rc_command "$1"
