#!/bin/sh

pidfile="$1"
shift

period="$1"
shift

slaves="$@"

executable="/usr/libexec/hprop"

if [ -z "$pidfile" -o -z "$period" -o -z "$slaves" ]; then
	echo "USAGE: $0 <pidfile> <period> <slave> [slave] [slave] ..."
	exit 1
fi

while true; do
	$executable $slaves
	sleep $period
done &

echo $! >$pidfile
