#!/bin/sh
#
# $FreeBSD: head/mail/exim/files/exim.in 340872 2014-01-24 00:14:07Z mat $
#

# PROVIDE: advancedfiltering_smtp
# REQUIRE: LOGIN
# KEYWORD: shutdown
#	we make mail start late, so that things like .forward's are not
#	processed until the system is fully operational

#
# Add the following lines to /etc/rc.conf to enable exim:
#
#advancedfiltering_smtp_exim_enable="YES"
#
# See exim(8) for flags
#

. /etc/rc.subr

name=advancedfiltering_smtp_exim
rcvar=advancedfiltering_smtp_exim_enable
command=/usr/local/sbin/exim
pidfile=/usr/local/advancedfiltering/smtp/exim/exim.pid
required_dirs="/usr/local/advancedfiltering/smtp/exim/log /usr/local/advancedfiltering/smtp/exim/spool"
required_files=/usr/local/advancedfiltering/smtp/exim/configure
stop_postcmd=stop_postcmd
extra_commands="reload"

stop_postcmd()
{
  rm -f $pidfile
}

# read settings, set default values
load_rc_config $name

: ${advancedfiltering_smtp_exim_enable="NO"}
: ${advancedfiltering_smtp_exim_flags="-bd -q30m -C /usr/local/advancedfiltering/smtp/exim/configure -oP /usr/local/advancedfiltering/smtp/exim/exim.pid"}

run_rc_command "$1"
