
EXTRA_PATCHES+=	${FILESDIR}/smtp_host_specific_port-4.80.1.patch
EXTRA_PATCHES+=	${FILESDIR}/tls_in_peerdn-4.82.patch
EXTRA_PATCHES+=	${FILESDIR}/server_cipher_list-4.82.diff
EXTRA_PATCHES+=	${FILESDIR}/switch_ssl_ctx-4.82.diff

pre-everything::
