
# required
EXTRA_PATCHES+=${FILESDIR}/openssl_peercert_peerdn-4.84.diff
EXTRA_PATCHES+=${FILESDIR}/tls_field_from_dn-4.84.diff
EXTRA_PATCHES+=${FILESDIR}/host_port-4.84.diff

# optional
EXTRA_PATCHES+=${FILESDIR}/smtp_host_specific_port-4.80.1.patch
EXTRA_PATCHES+=${FILESDIR}/tls_in_peerdn-4.82.patch
EXTRA_PATCHES+=${FILESDIR}/server_cipher_list-4.82.diff
EXTRA_PATCHES+=${FILESDIR}/switch_ssl_ctx-4.82.diff
EXTRA_PATCHES+=${FILESDIR}/vrfy_addr-4.84.diff

pre-everything::
